name: jDeploy npm Publish

on:
   push:
      branches:
         - '*-snapshot'
      tags:
         - 'v*'

concurrency:
   group: jdeploy-npm-${{ github.repository }}
   cancel-in-progress: false

jobs:
   publish:
      permissions:
         contents: read
         id-token: write
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v3
         - name: Set up JDK
           uses: actions/setup-java@v3
           with:
              java-version: '11'
              distribution: 'temurin'
         - name: Build with Maven
           run: mvn clean package -DskipTests
         - name: Publish to npm
           uses: shannah/jdeploy@master
           with:
              deploy_target: npm
              npm_token: ${{ secrets.NPM_TOKEN }}
